runtime: nodejs16

instance_class: F2

env_variables: 
  BUCKET_NAME: "angularapp-368104.appspot.com"

handlers:
- url: /
  static_files: dist/app/index.html
  upload: dist/app/index.html

- url: /
  static_dir: dist/app